name: pur
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - pip
  - pycbc
  - lalsuite
  - ligo-common
  - termcolor
  - pyseobnr
  - htcondor-24.*
  - sympy
  - bilby
  - bilby_pipe=1.8.0
  - python-nds2-client
  - python-ldas-tools-framecpp
